### ISSUE TITLE
ValveVpk Dispose still occupies memory?

### ISSUE THREAD

**Issue by KashimuraBaka** [ValveResourceFormat/ValvePak#20]
### Bug explanation 
When using `Package.AddFile()`, I found that if I add a single file and then destroy it through `Package.Dispose()`, wait for a while and GC will automatically recycle it.
But if I add multiple files and then destroy them, GC will not recycle them no matter how long I wait.
Even if I manually instruct GC, it will not recycle them.
If the user is operating multiple VPK files, this problem will occupy a large amount of memory and cause significant delays when using the program, thus affecting the overall user experience.

So, is there a good way to read files into memory for recycling, or other methods to read files to reduce memory overhead?
Thanks for taking the time to reply!

**Comment by xPaw** [comment]
Provide a working minimal repro please.

**Comment by KashimuraBaka** [comment]
# Code Sample
```
public void AddPackageFiles()
{
    using var package = new Package();
    package.AddFile("1.dat", File.ReadAllBytes("G:/test/1.dat"));
    package.AddFile("2.dat", File.ReadAllBytes("G:/test/2.dat"));
    package.AddFile("3.dat", File.ReadAllBytes("G:/test/3.dat"));
}
```
![2](https://github.com/user-attachments/assets/105a2acf-6970-4755-9548-c608d9b0ebae)

Just some simple writing to files, no saving operation.
And after writing is completed, the value of Package.FileDataSectionSize does not change.
This makes it impossible to detect the remaining capacity of the Package, preventing users from adding too many files and causing save failure.

**Comment by xPaw** [comment]
Adding a file doesn't use anything disposable (youre just adding a byte array), can you verify with a memory profiler that the object is staying alive and it's not .NET keeping the memory block allocated for it to be reused?

**Comment by KashimuraBaka** [comment]
The reference was not found in the alive object. The method was called through a component event.
![1](https://github.com/user-attachments/assets/601de6c8-de2c-43a3-94ee-fab46c9dcba3)

I also tried using ValvePack's Source 2 Viewer tool.
When I tried to create a new VPK package and add files, I saved and closed it.
The memory was also constantly occupied.
![1](https://github.com/user-attachments/assets/46d130c3-9876-4d78-bdf6-c2f79835b8b9)

**Comment by xPaw** [comment]
It does show up as dead LOH:

![image](https://github.com/user-attachments/assets/9a07d8ef-1d46-40b1-8cff-4955eb27d932)

This doesn't seem to be an issue with the library. The runtime manages the dead memory.

**Comment by KashimuraBaka** [comment]
Is there any other gentle way to create a VPK Package? 
This problem has also persisted for several days. Seeking help through the forum did not provide a good solution.
Users also often complain that their memory tools give warnings because of this problem.

There is another question just now, is it feasible to calculate the `FileDataSectionSize` method after `AddFile`? Will it affect other functions?

**Comment by xPaw** [comment]
You can track of the length of the files you are adding.

As for memory, is it actually causing an issue because the runtime should just be reusing the memory.

**Comment by KashimuraBaka** [comment]
OK, thank you.
It seems that we can only use other methods to soothe user memory anxiety.

**Comment by xPaw** [comment]
fwiw if you wait a couple of minutes, the memory in task manager does go down, i don't know why GC.Collect isn't collecting it.

https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap

**Comment by SamboyCoding** [comment]
If you haven't tried it, try `GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true)` and see if that does it. Normal GC.Collect doesn't necessarily do higher generations (which LOH is considered to be).

**Comment by KashimuraBaka** [comment]
Thanks for your guidance, After trying the above code.
I found that bytes has indeed been collected in the memory monitor, but the strange thing is that the memory submitted by the program is still occupied and has not been released.
![2](https://github.com/user-attachments/assets/a8b9e54a-4990-4c2d-985f-2e59314c9a6b)
![1](https://github.com/user-attachments/assets/dc3a8986-35f9-4e7a-b504-43b18e780954)
